# Generated by Django 5.1.1 on 2025-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_site_on", models.BooleanField(default=True)),
            ],
        ),
    ]
