# Generated by Django 5.1.1 on 2025-04-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceo", "0002_sitecontrol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("platform", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("contacted", "Contacted"),
                            ("project_started", "Project Started"),
                            ("continuing", "Contact is Continuing"),
                            ("finished", "Finished"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("assistant_name", models.CharField(max_length=255)),
                ("notes", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
