# Generated by Django 5.1.1 on 2024-12-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="date",
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="summ",
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
